### ISSUE TITLE
Tracking issue for Qt6 bugs

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#489]
Copied from #486. The idea is to address the different issues in many small PRs and keep tracking progress here.

I discovered all of these issues when testing with the desktop example. 

I have started testing against my application (psiexperiment) and may have more to report later.

### Examples to check
- [ ] aliases
- [ ] applib
- [ ] dynamic
- [ ] functions
- [ ] layout
- [ ] stdlib
- [ ] styling
- [ ] templates
- [ ] tutorial
- [x] widgets
- [ ] workbench

### Broken examples
- [ ] `drag_and_drop.enaml` (drag and drop broken)
- [ ] `file_dialog.enaml` (browse button broken)
- [ ] `flow_area.enaml` (changing flow layout)
- [ ] `image_view.enaml` (set to None)
- [ ] `ipython_console.enaml` (possibly just need to install qtconsole),
- [ ] `vtk_canvas.enaml` (most likely need to install vtk)
- [ ] `web_view.enaml`

**Comment by MatthieuDartiailh** [comment]
All examples have been checked, we are just left with the issues to address.

**Comment by MatthieuDartiailh** [comment]
The image view is not a real issue and the functio tracing never worked as far as I can tell. So I will close once #495 goes in and make a patch release.

**Comment by MatthieuDartiailh** [comment]
0.15.1 is out with all the above fixes. Thanks all that helped fixing Qt6 support.
